apiVersion: 1

policies:
  - orgId: 1
    receiver: grafana-default-email
    group_by: ['alertname', 'http_route']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      # Route all order-tracker 5xx alerts to the incident responder webhook
      - receiver: incident-responder-webhook
        matchers:
          - alertname = "5xx Responses Detected"
        group_wait: 10s
        group_interval: 1m
        repeat_interval: 10m
        continue: false
